set_property PACKAGE_PIN E3 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
#set_property IOSTANDARD LVCMOS33 [get_ports signal1]
#set_property IOSTANDARD LVCMOS33 [get_ports signal2]
#set_property IOSTANDARD LVCMOS33 [get_ports signal3]
#set_property PACKAGE_PIN C17 [get_ports signal1]
#set_property PACKAGE_PIN D18 [get_ports signal2]
#set_property PACKAGE_PIN E18 [get_ports signal3]

set_property PACKAGE_PIN P17 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports servo1]
set_property IOSTANDARD LVCMOS33 [get_ports servo2]
set_property IOSTANDARD LVCMOS33 [get_ports servo3]
set_property IOSTANDARD LVCMOS33 [get_ports signal1LED]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property PACKAGE_PIN M17 [get_ports reset]
set_property PACKAGE_PIN C17 [get_ports servo1]
set_property PACKAGE_PIN D18 [get_ports servo2]
set_property PACKAGE_PIN E18 [get_ports servo3]
set_property IOSTANDARD LVCMOS33 [get_ports startLED]
set_property PACKAGE_PIN V11 [get_ports signal1LED]

set_property IOSTANDARD LVCMOS33 [get_ports signal2LED]
set_property PACKAGE_PIN V12 [get_ports signal2LED]
set_property PACKAGE_PIN V15 [get_ports startLED]
set_property PACKAGE_PIN P17 [get_ports start]
