set_property PACKAGE_PIN G17 [get_ports arduino_reset]
set_property PACKAGE_PIN E3 [get_ports clock]
set_property PACKAGE_PIN H17 [get_ports onLED]
set_property PACKAGE_PIN N17 [get_ports reset]
set_property PACKAGE_PIN C17 [get_ports servo1]
set_property PACKAGE_PIN D18 [get_ports servo2]
set_property PACKAGE_PIN V11 [get_ports signal1LED]
set_property PACKAGE_PIN V12 [get_ports signal2LED]
set_property PACKAGE_PIN P17 [get_ports start]
set_property PACKAGE_PIN P18 [get_ports stop]

set_property IOSTANDARD LVCMOS33 [get_ports arduino_reset]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports onLED]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports servo1]
set_property IOSTANDARD LVCMOS33 [get_ports servo2]
set_property IOSTANDARD LVCMOS33 [get_ports servo3]
set_property IOSTANDARD LVCMOS33 [get_ports signal1LED]
set_property IOSTANDARD LVCMOS33 [get_ports signal2LED]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports stop]

set_property PACKAGE_PIN E18 [get_ports servo3]


set_property IOSTANDARD LVCMOS33 [get_ports audioEn]
set_property IOSTANDARD LVCMOS33 [get_ports audioOut]
set_property PACKAGE_PIN D12 [get_ports audioEn]
set_property PACKAGE_PIN A11 [get_ports audioOut]
