# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Study/Duke/+1/ECE350/Project/final_project/final_project.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Study/Duke/+1/ECE350/Project/final_project/final_project.cache/wt [current_project]
set_property parent.project_path D:/Study/Duke/+1/ECE350/Project/final_project/final_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Study/Duke/+1/ECE350/Project/final_project/final_project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  {D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/Memory Files/basiccount.mem}
  {D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/Memory Files/servo1.mem}
  {D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/Memory Files/minute.mem}
}
read_verilog -library xil_defaultlib {
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/DXpipe.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/FDpipe.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/MWpipe.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/PWpipe.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/RAM.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/ROM.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/XMpipe.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/alu.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/bitwise_and.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/bitwise_not.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/bitwise_or.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/branchbypass.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/branchcomparator.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/bypassctrl.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/cla_32.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/cla_slice.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/comparator.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/counter.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/cpgenerate.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/decoder.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/dffe_ref.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/divider.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/eight_bit_cla.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/multdiv.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/multdivctrl.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/multiplier.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/mux_2.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/mux_2_2.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/mux_4.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/mux_4_2.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/mux_8.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/nextPC.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/partialProd.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/partialQuotient.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/processor.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/reg_32.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/regfile.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/secondctrl.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/servooutput.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/shift_left_logical.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/shift_right_arithmic.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/stallctrl.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/sum_unit.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/tristatebuf.v
  D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/sources_1/imports/ece350-project/Wrapper.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/constrs_1/new/NexysA7.xdc
set_property used_in_implementation false [get_files D:/Study/Duke/+1/ECE350/Project/final_project/final_project.srcs/constrs_1/new/NexysA7.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
